name: Release

on:
  release:
    types: [created]

jobs:
  build-linux:
    name: Upload Linux binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/release/usage-tracker
        asset_name: usage-tracker-${{ github.event.release.tag_name }}-linux
        asset_content_type: application/x-elf
  build-windows:
    name: Upload Windows binary
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/release/usage-tracker.exe
        asset_name: usage-tracker-${{ github.event.release.tag_name }}-windows.exe
        asset_content_type: application/vnd.microsoft.portable-executable
